# Generated by Django 4.2.5 on 2023-10-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgoria',
            new_name='Categoria',
        ),
    ]
